# Copyright 1999-2013 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.3.2

CABAL_FEATURES="bin"
inherit haskell-cabal

DESCRIPTION="Happy Haskell programming on Emacs/Vim"
HOMEPAGE="http://www.mew.org/~kazu/proj/ghc-mod/"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=""
DEPEND="${RDEPEND}
		>=dev-haskell/cabal-1.6
		dev-haskell/convertible
		dev-haskell/ghc-paths
		dev-haskell/ghc-syb-utils
		>=dev-haskell/hlint-1.7.1
		dev-haskell/io-choice
		dev-haskell/regex-posix
		dev-haskell/syb
		dev-haskell/transformers
		>=dev-lang/ghc-6.12.1"
