# Copyright 1999-2011 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header:  $

# ebuild generated by hackport 0.2.13

EAPI="3"

CABAL_FEATURES="bin"
inherit haskell-cabal

DESCRIPTION="Simple utility to fix BROKEN package dependencies."
HOMEPAGE="http://hackage.haskell.org/package/ghc-pkg-autofix"
SRC_URI="http://hackage.haskell.org/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=""
DEPEND="${RDEPEND}
		>=dev-haskell/cabal-1.8
		<dev-haskell/cabal-2
		=dev-haskell/parsec-3*
		=dev-haskell/split-0.1*
		>=dev-lang/ghc-6.10.1"

src_prepare() {
	sed -e 's/process >= 1.0 && < 1.1/process >= 1.0/' \
		-i "${S}/${PN}.cabal"
}
