# Copyright 1999-2011 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header:  $

# ebuild generated by hackport 0.2.13

EAPI="3"

CABAL_FEATURES="lib profile haddock hscolour"
inherit haskell-cabal

DESCRIPTION="Binding to the Gtk+ graphical user interface library."
HOMEPAGE="http://projects.haskell.org/gtk2hs/"
SRC_URI="http://code.haskell.org/~duncan/gtk2hs/${P}.tar.gz"

LICENSE="LGPL-2.1"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE="+gio"

RDEPEND=">=dev-haskell/cairo-0.12.0
		<dev-haskell/cairo-0.13
		>=dev-haskell/gio-0.12.0
		<dev-haskell/gio-0.13
		>=dev-haskell/glib-0.12.0
		<dev-haskell/glib-0.13
		dev-haskell/mtl
		>=dev-haskell/pango-0.12.0
		<dev-haskell/pango-0.13
		>=dev-lang/ghc-6.10.1
		dev-libs/glib
		x11-libs/gtk+"
DEPEND="${RDEPEND}
		>=dev-haskell/cabal-1.8
		dev-haskell/gtk2hs-buildtools"

src_configure() {
	# Upstream has this enabled, so we might as well force it enabled to be sure.
	cabal_src_configure \
		--flags=deprecated \
		$(cabal_flag gio have-gio)
}
