# Copyright 1999-2011 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header:  $

# ebuild generated by hackport 0.2.13

EAPI="3"

CABAL_FEATURES="lib profile haddock hscolour"
inherit haskell-cabal git

EGIT_REPO_URI="git://github.com/HeinrichApfelmus/reactive-banana.git"
EGIT_PATCHES="${FILESDIR}/${P}-fix-import.patch"

DESCRIPTION="Small but solid library for functional reactive programming (FRP)."
HOMEPAGE="http://haskell.org/haskellwiki/Reactive-banana"

LICENSE="BSD"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND="=dev-haskell/quickcheck-2.4*
		=dev-haskell/transformers-0.2*
		>=dev-lang/ghc-7.0.1"
DEPEND="${RDEPEND}
		>=dev-haskell/cabal-1.6"

src_prepare() {
	git_src_prepare
	S="${WORKDIR}/${P}/${PN}"
}
