# Copyright 1999-2010 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.16.4

EAPI="2"

MODULE_AUTHOR="MIROD"


inherit perl-module

DESCRIPTION="add XPath support to HTML::TreeBuilder"

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="~amd64"
IUSE=""

DEPEND=">=dev-perl/XML-XPathEngine-0.12
	dev-perl/HTML-Tree
	dev-lang/perl"
