# Copyright 1999-2011 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header:  $

# ebuild generated by hackport 0.2.13

EAPI="3"

CABAL_FEATURES="lib profile haddock hscolour"
inherit haskell-cabal git

EGIT_REPO_URI="git://github.com/ekmett/reactive.git"

DESCRIPTION="Push-pull functional reactive programming"
HOMEPAGE="http://haskell.org/haskellwiki/reactive"

LICENSE="AGPL-3"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND="=dev-haskell/comonad-1.1*
		>=dev-haskell/data-default-0.2.0.1
		>=dev-haskell/pointed-0.1.3
		>=dev-haskell/semigroupoids-1.2.2
		<dev-haskell/semigroupoids-1.3
		>=dev-haskell/semigroups-0.5
		>=dev-haskell/streams-0.7.2
		>=dev-haskell/typecompose-0.8.0
		>=dev-haskell/unamb-0.1.5
		>=dev-haskell/vector-space-0.5
		>=dev-lang/ghc-6.10.1"
DEPEND="${RDEPEND}
		>=dev-haskell/cabal-1.2"

src_prepare() {
	sed -e 's/data-default >= 0.2.0.1 && < 0.3/data-default >= 0.2.0.1/' \
		-e 's/pointed >= 0.1.3 && < 0.2/pointed >= 0.1.3/' \
		-e 's/semigroups >= 0.5 && < 0.6/semigroups >= 0.5/' \
		-e 's/streams >= 0.7.2 && < 0.8/streams >= 0.7.2/' \
		-i "${S}/${PN}.cabal"
	sed -e '1i {-# LANGUAGE StandaloneDeriving, DeriveDataTypeable #-}' \
		-i "${S}/src/FRP/Reactive/Internal/Chan.hs"
	sed -e '1i {-# LANGUAGE FlexibleInstances #-}' \
		-i "${S}/src/FRP/Reactive/Num.hs"
}
